# Generated by Django 3.0.3 on 2020-03-28 11:18

from django.db import migrations, models
import django.db.models.deletion
import war.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DMG', models.IntegerField(validators=[war.models.validate_zero])),
                ('DEX', models.IntegerField(validators=[war.models.validate_zero])),
                ('DEF', models.IntegerField(validators=[war.models.validate_zero])),
                ('name', models.CharField(max_length=15, unique=True)),
                ('race', models.CharField(max_length=15)),
                ('HP', models.IntegerField()),
                ('LVL', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DMG', models.IntegerField(validators=[war.models.validate_zero])),
                ('DEX', models.IntegerField(validators=[war.models.validate_zero])),
                ('DEF', models.IntegerField(validators=[war.models.validate_zero])),
                ('name', models.CharField(max_length=15)),
                ('race', models.CharField(max_length=15)),
                ('HP', models.IntegerField()),
                ('opponent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='war.Hero')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
